spring.application.name=backend

spring.datasource.url = jdbc:postgresql://ep-dawn-scene-aqi784ja-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username = neondb_owner
spring.datasource.password = npg_F3ZrDPVAJh5v

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true